# Generated by Django 4.1.4 on 2023-09-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date_of_birth',
        ),
    ]
