# Generated by Django 4.1.4 on 2023-09-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_member_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/'),
        ),
    ]
