# Generated by Django 4.1.4 on 2023-09-29 13:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_commemts_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commemts',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
