# Generated by Django 4.2.4 on 2023-09-30 03:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_commemts_description_alter_task_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commemts',
            options={'verbose_name': 'Comment'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task'},
        ),
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'verbose_name': 'Task Status', 'verbose_name_plural': 'Task Status'},
        ),
        migrations.CreateModel(
            name='CommentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='file/')),
                ('attached_at', models.DateTimeField(default=datetime.datetime.now)),
                ('commemt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.commemts')),
            ],
        ),
    ]
