# Generated by Django 4.1.4 on 2023-10-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_commemts_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='files',
            field=models.ImageField(blank=True, null=True, upload_to='file/'),
        ),
    ]
