# Generated by Django 4.1.4 on 2023-09-19 11:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default='', max_length=100, null=True)),
                ('description', tinymce.models.HTMLField()),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectstatus')),
            ],
        ),
    ]
