# Generated by Django 4.1.4 on 2023-09-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
