# Generated by Django 4.2.5 on 2023-09-21 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_file_project_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='files',
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
