# Generated by Django 4.1.4 on 2023-09-22 08:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_project_files_file_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='adminurl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='extra_credential',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
