# Generated by Django 4.1.4 on 2023-09-29 13:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='extra_credential',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
